_target_: src.models.diffusion.TransformerDiffusionGenerator

defaults:
  - _self_
  - architecture: transformer.yaml

max_sigma: 80
min_sigma: 1.0e-5
ema_sync: 0.999
p_mean: -1.2
p_std: 1.2

# Sampler and noise schedule for the generation
sampler_function:
  _target_: src.utils.diffusion.sample_heun
  _partial_: True

sigma_function:
  _target_: src.utils.diffusion.get_sigmas_karras
  _partial_: True
  n_steps: 50
  rho: 7

cosine_config:
  outp_dim: 16
  frequency_scaling: exponential

normaliser_config:
  max_n: 2000_000

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 0

# Config dicts to pass to utils and pytorch lightning
sched_config:
  utils:
    name: warmup
    num_steps: 50_000
  lightning:
    monitor: valid/noise_loss
    interval: step
    frequency: 1
