seed: 12345
project_name: pc_jedi
network_name: paper_cd_dpmpp2m30_150
ckpt_path: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150/checkpoints/last-v1.ckpt
precision: medium
compile: null
full_resume: false
trainer:
  _target_: pytorch_lightning.Trainer
  min_epochs: 1
  max_epochs: 9999
  enable_progress_bar: true
  accelerator: auto
  devices: auto
  gradient_clip_val: 10
  precision: 16-mixed
  check_val_every_n_epoch: 50
  default_root_dir: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150/
model:
  _target_: src.models.consistency.ConsistencyDroid
  teacher_checkpoint: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_model_150/checkpoints/last-v2.ckpt
  loss_name:
    _target_: src.loss.MaskedLossWrap
    _partial_: true
    loss_fn:
      _target_: torch.nn.MSELoss
      _partial_: true
      reduction: none
  min_sigma: 1.0e-05
  max_sigma: 80
  ema_sync: 0.99
  n_gen_steps: 3
  sampler_function:
    _target_: src.utils.k_diffusion.one_step_dpm_2
    _partial_: true
  sigma_function:
    _target_: src.utils.k_diffusion.get_sigmas_karras
    _partial_: true
    n_steps: 30
    rho: 7
  optimizer:
    _target_: torch.optim.RAdam
    _partial_: true
    lr: 0.0001
    weight_decay: 0
  sched_config:
    utils:
      name: warmup
      num_steps: 100
    lightning:
      monitor: valid/total_loss
      interval: step
      frequency: 1
datamodule:
  _target_: src.datamodules.jet_net.JetNetDataModule
  data_conf:
    log_squash_pt: true
    high_as_context: true
    n_jets: null
    one_hot_last: true
    jetnet_config:
      jet_type:
      - g
      - q
      - t
      - w
      - z
      data_dir: /srv/beegfs/scratch/groups/rodem/datasets/jetnet/
      num_particles: 150
      split_fraction:
      - 0.7
      - 0.15
      - 0.15
      particle_features:
      - etarel
      - phirel
      - ptrel
      jet_features:
      - pt
      - eta
      - mass
      - num_particles
      - type
  loader_kwargs:
    pin_memory: true
    batch_size: 256
    num_workers: 0
    drop_last: true
loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    entity: jet-diffusion
    offline: false
    id: 53yxlpsx
    log_model: false
    project: pc_jedi
    name: paper_cd_dpmpp2m30_150
    save_dir: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150/
    resume: true
paths:
  data_dir: /srv/beegfs/scratch/groups/rodem/anomalous_jets/virtual_data
  output_dir: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints
  root_dir: /home/users/l/leighm/JetDiffusion
  full_path: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150/
callbacks:
  latest_model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150//checkpoints
    save_on_train_epoch_end: true
    filename: last
  best_model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: /srv/beegfs/scratch/groups/rodem/jet_diffusion/checkpoints/pc_jedi/paper_cd_dpmpp2m30_150//checkpoints
    filename: best_{epoch:03d}
    monitor: valid/total_loss
    mode: min
    save_weights_only: true
    auto_insert_metric_name: false
    save_last: false
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
